#!/bin/sh
if [ $# -ne 1 ]; then
sta=`curl --header "Authorization: Bearer $token" \
-sS https://$instanceURL/api/v1/timelines/home?limit=5`
else
sta=`curl --header "Authorization: Bearer $token" \
-sS https://$instanceURL/api/v1/timelines/home?limit=$1`
fi

echo $sta | sed -e 's/,/\n/g' | grep -v '"note"' | grep -v '"url"' | grep -v '"followers_count"' | grep -v '"header"' |\
grep -v '"header_static"' | grep -v '"avatar_static"' | grep -v '"avatar"' | grep -v '"mentions"'| grep -v '"media_attachments"' |\
grep -v '"following_count"' | grep -v '"acct"' | grep -v '"locked"' | grep -v '"favourites_count"' | grep -v '"reblog"' |\
grep -v '"tags"' | grep -v '"statuses_count"' | grep -v '"in_reply_to_id"' | grep -v '"reblogs_count"' | grep -v '"application"' |\
grep -v '"id"' | grep -v '"website"' | grep -v '"language"' | grep -v '"muted"' | grep -v '"favourited"' | grep -v '"visibility"' |\
grep -v '"reblogged"' | grep -v '"in_reply_to_account_id"' | grep -v '"sensitive"' | grep -v '"spoiler_text":""' | grep -v '"uri"' |\
grep -v '"display_name":""' | grep -v '"created_at"' | grep -v '"aspect"' | grep -v '"size"'| grep -v '"height"'|\
grep -v '"small"'| grep -v '"meta"'| grep -v '"remote_url":""'| grep -v '"preview_url"'| grep -v '"type"'|\
sed -e 's/\(:objectId=[0-9]\+:objectType=Status\)/ /g' -e 's/\\u003cp\\u003e//g' -e 's/\\u003c\/p\\u003e//g' -e 's/"content":"/Toot: /g'|\
sed -e 's/"username":"/@/g'|\
sed -e 's/"display_name":"/Name: /g' -e 's/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/\n/g' |\
sed -e ':a' -e 'N' -e '$!ba' -e 's/\n\n/\n/g'|\
sed -e 's/"//g' -e 's/\\u003cbr\\u003e/\n/g' -e 's/spoiler_text:/\nCW Text: /g'
exit 0
