#!/bin/sh
if [ $# -ne 1 ]; then
sta=`curl -F "status=null" -sS $InstanceURL --header "Authorization: Bearer $TOKEN" -o /dev/null -w '%{http_code}'`
else
sta=`curl -F "status=$1" -sS $InstanceURL --header "Authorization: Bearer $TOKEN" -o /dev/null -w '%{http_code}'`
fi
if [ $sta = 200 ]; then 
echo "200 OK!"
else
echo "Error!!"
fi
exit 0
